#!/bin/bash

SCRIPT=`realpath $0`

readonly BASH_BINARY="$(which bash)"
declare -x PREVIEW_ID="preview"

declare -x TMP_FOLDER="/tmp/vimg"
mkdir -p $TMP_FOLDER

function draw_preview {

    if [[ "$1" == "imagepreview" ]]; then
      viu -w ${5} -h ${6} "${2}"

    elif [[ "$1" == "gifpreview" ]]; then
      # This is static for now, feel free to re-introduce FIFO to make
      # animations work again, plaing viu gifs (removing the -s flag) causes
      # the preview window to scroll weirdly
      viu -s -w ${5} -h ${6} "${2}"

    elif [[ "$1" == "videopreview" ]]; then
      path="${2##*/}"
      echo -e "Loading preview..\nFile: $path"
      ffmpegthumbnailer -i "$2" -o "${TMP_FOLDER}/${path}.png" -s 0 -q 10
      clear
      viu -w ${5} -h ${6} "${TMP_FOLDER}/${path}.png"


    elif [[ "$1" == "pdfpreview" ]]; then
      path="${2##*/}"
        echo -e "Loading preview..\nFile: $path"
        [[ ! -f "${TMP_FOLDER}/${path}.png" ]] && pdftoppm -png -singlefile "$2" "${TMP_FOLDER}/${path}"
        clear
        viu -w ${5} -h ${6} "${TMP_FOLDER}/${path}.png"
    fi
}

function parse_options {
    extension="${1##*.}"
    case $extension in
    jpg | png | jpeg | webp)
        draw_preview  imagepreview "$1" $2 $3 $4 $5
    ;;

    gif)
        draw_preview  gifpreview "$1" $2 $3 $4 $5
    ;;

    avi | mp4 | wmv | dat | 3gp | ogv | mkv | mpg | mpeg | vob |  m2v | mov | webm | mts | m4v | rm  | qt | divx)
        draw_preview  videopreview "$1" $2 $3 $4 $5
    ;;

    pdf | epub)
        draw_preview  pdfpreview "$1" $2 $3 $4 $5
    ;;

    *)
    echo -n "unknown file $1"
    ;;
    esac
}

# trap finalise EXIT
# start_ueberzug
parse_options "${@}"
read
